image: google/cloud-sdk:latest

stages:
  - checkout
  - build
  - deploy

variables:
  PROJECT_ID: "even-kite-476205-d1"
  REGION: "us-east1"
  REPO: "llmops-repo"
  REGISTRY: "us-east1-docker.pkg.dev"
  CLUSTER: "dev-gke01"

checkout_code:
  stage: checkout
  script:
    - echo "Code Checked out.."

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache curl python3 py3-crcmod bash
    - curl -sSL https://sdk.cloud.google.com | bash > /dev/null
    - export PATH="$PATH:/root/google-cloud-sdk/bin"
    - echo "$GCP_SA_KEY" | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
    - gcloud auth configure-docker $REGISTRY
  script:
    - docker build -t $REGISTRY/$PROJECT_ID/$REPO/llmops-app:latest .
    - docker push $REGISTRY/$PROJECT_ID/$REPO/llmops-app:latest

deploy_to_gke:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo "$GCP_SA_KEY" | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
    - gcloud auth configure-docker $REGISTRY
  script:
    - gcloud container clusters get-credentials $CLUSTER --region $REGION --project $PROJECT_ID
    - kubectl apply -f kubernetes-deployment.yaml
